AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Ok to delete after Sept-18 2017
Parameters:
  GoogleClientId:
    Type: String
    Description: "OAuth 2.0 client id from Google"
    Default: "623591274072-ev6i9bsjsk8p0oaeh8h58nf0tn1vpkf5.apps.googleusercontent.com"
Resources:
  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      AllowUnauthenticatedIdentities: false
      SupportedLoginProviders:
        "accounts.google.com": !Ref GoogleClientId
  FederatedUserRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
        - Effect: Allow
          Action: "sts:AssumeRoleWithWebIdentity"
          Principal:
            Federated: "cognito-identity.amazonaws.com"
          Condition:
            StringEquals:
              "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
      Policies: 
        - PolicyName: "subscribe-to-topic"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                - "iot:Connect"
                - "iot:Subscribe"
                - "iot:Receive"
                Resource: "*"
  RoleAttachments:
    # Warning! this resource "cannot be updated"
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      Roles: {}
      IdentityPoolId: !Ref IdentityPool
      RoleMappings: 
        "accounts.google.com":
          AmbiguousRoleResolution: Deny
          Type: Rules
          RulesConfiguration:
            Rules:
            - MatchType: Equals
              Value: sourceallies.com
              Claim: hd
              RoleARN: !GetAtt FederatedUserRole.Arn
  IoTPolicy:
    Type: "AWS::IoT::Policy"
    Properties:
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action: "iot:*"
          Resource: !Join [':',
            - "arn:aws:iot"
            - !Ref: "AWS::Region"
            - !Ref: "AWS::AccountId"
            - "topic/${accounts.google.com:sub}"
          ]
Outputs:
  GoogleClientId:
    Description: OAuth Client ID to use when obtaining tokens
    Value: !Ref GoogleClientId
  IdentityPoolId:
    Description: ID of the Cognito Identity Pool that should be used to login
    Value: !Ref IdentityPool
  IoTPolicy:
    Description: Name of the IoT Policy
    Value: !Ref IoTPolicy
  